#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4096M

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.configuration-cache.parallel=true
org.gradle.caching=true
org.gradle.parallel=true

#Android
android.nonTransitiveRClass=true
